"""Reusable MAVLink helpers derived from pymavlink-utils examples.

Import from the repo root (same directory as main.py):

    from hex_mavlink import connect, arming, flight
    from hex_mavlink.arming import arm, wait_prearm

Original runnable scripts remain in pymavlink-utils/ unchanged.
"""

from hex_mavlink import (
    actuators,
    arming,
    connection,
    fence,
    flight,
    home,
    ipc,
    messages,
    mission,
    modes,
    parameters,
    rally,
    status,
)
from hex_mavlink._common import VehicleTimeout, dialect
from hex_mavlink.actuators import (
    build_rc_override,
    clamp_pwm,
    read_rc_channels,
    read_servo_outputs,
    repeat_relay,
    repeat_servo,
    send_rc_override,
    set_relay,
    set_servo,
)
from hex_mavlink.arming import (
    VEHICLE_ARM,
    VEHICLE_DISARM,
    arm,
    disarm,
    is_armed,
    wait_armed,
    wait_disarmed,
    wait_prearm,
)
from hex_mavlink.connection import (
    connect,
    connect_with_retry,
    detect_pixhawk_port,
    list_serial_port_candidates,
    open_pixhawk,
    recv_match_locked,
    start_gcs_heartbeat,
    wait_heartbeat,
    PixhawkConnectionError,
    DEFAULT_BAUD,
    DEFAULT_SERIAL_PORT,
)
from hex_mavlink.fence import (
    FENCE_ENABLE_MODES,
    get_fence,
    get_fence_count,
    set_fence_enabled,
    upload_fence,
)
from hex_mavlink.flight import (
    ANGLE_ABSOLUTE,
    ANGLE_RELATIVE,
    DIRECTION_CCW,
    DIRECTION_CW,
    DIRECTION_DEFAULT,
    PAUSE,
    RESUME,
    get_relative_altitude,
    goto_location,
    land,
    pause,
    resume,
    set_ground_speed,
    set_yaw,
    takeoff,
    wait_altitude,
    wait_at_location,
)
from hex_mavlink.home import (
    distance_from_home,
    get_home,
    get_vehicle_position,
    request_home,
    set_home,
)
from hex_mavlink.ipc import (
    create_ipc_connection,
    send_heartbeat_once,
    start_heartbeat_thread,
)
from hex_mavlink.messages import (
    recv_message,
    recv_message_dict,
    request_autopilot_version,
    request_data_stream,
    request_message,
    request_message_interval,
    send_banner,
    send_command_long,
)
from hex_mavlink.mission import (
    clear_mission,
    get_current_mission_item,
    get_mission,
    get_mission_count,
    set_current_mission_item,
    upload_mission,
    upload_mission_partial,
)
from hex_mavlink.modes import get_mode, set_mode, supported_modes
from hex_mavlink.parameters import get_param, request_param_list, set_param
from hex_mavlink.rally import get_rally_count, get_rally_points, upload_rally_points
from hex_mavlink.status import check_terrain, log_onboard_data, send_statustext

__all__ = [
    "VehicleTimeout",
    "dialect",
    "actuators",
    "arming",
    "connection",
    "fence",
    "flight",
    "home",
    "ipc",
    "messages",
    "mission",
    "modes",
    "parameters",
    "rally",
    "status",
    "connect",
    "connect_with_retry",
    "detect_pixhawk_port",
    "list_serial_port_candidates",
    "open_pixhawk",
    "recv_match_locked",
    "start_gcs_heartbeat",
    "wait_heartbeat",
    "PixhawkConnectionError",
    "DEFAULT_BAUD",
    "DEFAULT_SERIAL_PORT",
    "recv_message",
    "recv_message_dict",
    "send_command_long",
    "send_banner",
    "request_data_stream",
    "request_message_interval",
    "request_message",
    "request_autopilot_version",
    "request_param_list",
    "get_param",
    "set_param",
    "VEHICLE_ARM",
    "VEHICLE_DISARM",
    "wait_prearm",
    "arm",
    "disarm",
    "is_armed",
    "wait_armed",
    "wait_disarmed",
    "supported_modes",
    "get_mode",
    "set_mode",
    "takeoff",
    "land",
    "get_relative_altitude",
    "wait_altitude",
    "goto_location",
    "wait_at_location",
    "set_ground_speed",
    "set_yaw",
    "pause",
    "resume",
    "DIRECTION_CCW",
    "DIRECTION_DEFAULT",
    "DIRECTION_CW",
    "ANGLE_ABSOLUTE",
    "ANGLE_RELATIVE",
    "PAUSE",
    "RESUME",
    "get_mission_count",
    "get_mission",
    "upload_mission",
    "upload_mission_partial",
    "clear_mission",
    "get_current_mission_item",
    "set_current_mission_item",
    "FENCE_ENABLE_MODES",
    "get_fence_count",
    "get_fence",
    "upload_fence",
    "set_fence_enabled",
    "get_rally_count",
    "get_rally_points",
    "upload_rally_points",
    "request_home",
    "get_home",
    "set_home",
    "get_vehicle_position",
    "distance_from_home",
    "set_servo",
    "repeat_servo",
    "set_relay",
    "repeat_relay",
    "clamp_pwm",
    "build_rc_override",
    "send_rc_override",
    "read_rc_channels",
    "read_servo_outputs",
    "send_statustext",
    "log_onboard_data",
    "check_terrain",
    "create_ipc_connection",
    "send_heartbeat_once",
    "start_heartbeat_thread",
]

__version__ = "0.1.0"
